server:
  port: 9000
spring:
  application:
    name: eureka-server-9000
eureka:
  client:

    service-url:
      defaultZone: http://server1:9000/eureka/
      #, http://server3:9002/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: server1
