server:
  port: 9002
spring:
  application:
    name: eureka-server-9002

eureka:
 client:
  service-url:
    defaultZone: http://server1:9000/eureka/, http://server2:9001/eureka/
 instance:
   hostname: server3
